version: '3'
services:
    web:
        container_name: web_cgi
        build:
            context: .
            dockerfile: ngnix.Dockerfile
            
        volumes:
            - ./../html:/var/www
            - ./../log/web:/var/log/nginx/web
        ports:
            - "8080:80"

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: test-mysql
        environment:
#          - MYSQL_USER=test
#          - MYSQL_PASSWORD=testtest
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=test
        ports:
          - '3306'
        volumes:
          - /home/user/dev/project_one/db_dump/test.sql:/docker-entrypoint-initdb.d/test.sql
